# Name of the workflow (visible in Github Actions tab)
name: Deploy to Github Pages


# Trigger: when this workflow should run
on: 
  push:                 # Run when someone pushes commits
    branches:
      - main            # Only run if the push is to the 'main' branch
    paths:              # Only run if these files are changed
      - index.html      # Here we only care about changes to index.html

permissions:
  contents: read
  pages: write
  id-token: write

# Define the jobs for this workflow
jobs:
  deploy:     
    runs-on: ubuntu-latest # The virtual machine the job will run on


    steps:

      # Step 1: check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Github Pages
      - name: Setup Github Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload Github Pages artifact
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
      
      # Step 4: Deploy to Github Pages
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4